### ISSUE TITLE
bsv-p2p: ERROR Error: Invalid payload

### ISSUE THREAD

**Issue by mshahzaib101** [kevinejohn/bsv-p2p#1]
Hi, 
my node was working fine till last week but it is giving this error

 bsv-p2p: Connecting to seed.bitcoinsv.io:8333
 bsv-p2p: Connected to seed.bitcoinsv.io:8333
 connected
 bsv-p2p: ERROR Error: Invalid payload
    at Object.read (/home/mshahzaib/Desktop/upworkRobinKohzeProject/MetaShard/MetaShard_server/node_modules/bsv-p2p/src/messages/version.js:47:24)
    at Peer.readMessage (/home/mshahzaib/Desktop/upworkRobinKohzeProject/MetaShard/MetaShard_server/node_modules/bsv-p2p/src/index.js:159:33)
    at Socket.<anonymous> (/home/mshahzaib/Desktop/upworkRobinKohzeProject/MetaShard/MetaShard_server/node_modules/bsv-p2p/src/index.js:357:23)
    at Socket.emit (events.js:315:20)
    at addChunk (internal/streams/readable.js:309:12)
    at readableAddChunk (internal/streams/readable.js:284:9)
    at Socket.Readable.push (internal/streams/readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
bsv-p2p: Disconnected from seed.bitcoinsv.io
disconnects

I have tried connecting with other nodes also but get same error
const nodes = [`seed.bitcoinsv.io`, `seed.cascharia.com`, `seed.satoshisvision.network`]
thank you

**Comment by gr1m1um** [comment]
same

**Comment by mshahzaib101** [comment]
I resolved this issue,
Just go into bsv-p2p library code and search for "invalid payload"

In every file just comment that line, it will be something like throw error, just comment it and then run..

**Comment by kevinejohn** [comment]
I just fixed this in v0.0.4
